apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: helloworld-v2
  name: helloworld-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-v2
    spec:
      containers:
        - image: kelseyhightower/helloworld:v2 
          name: helloworld-v2
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-v2
  name: helloworld-v2
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31438
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld-v2
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
