version: "0.2"
services:
 db:
  image: mysql:5.7
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: rootpassword
   MYSQL_DATABASE: lab1
   MYSQL_USER: lab1_user
   MYSQL_PASSWORD: password
 wordpress:
  depends_on:
   - db
  image: wordpress:latest
  ports:
   - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: lab1_user
   WORDPRESS_DB_PASSWORD: password
   WORDPRESS_DB_NAME: lab1
volumes:
 db_data: {}

