apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw
spec:
  selector:
    matchLabels:
      app: hw
  replicas: 1
  
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
        - name: hw
          image: karthequian/helloworld:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hw
spec:
  selector:
    app: hw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer


  