apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: helloworld-v2
    version: v2
  name: helloworld-v2
  namespace: web-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-v2
        version: v2
    spec:
      containers:
        - image: kelseyhightower/helloworld:v2 
          name: helloworld-v2
          ports:
            - containerPort: 8080
              name: http